defaults:
  text_file: results.txt
  num_repeats: 5
  pre_train_eval: false
  random_state: 42
  scalar: 0
  eval_dataset_size:
  eval_dataset_subset: 100
  num_samples: 500
  train_lm_eval_task:
  proportion:

validation:
  required_keys:
    - model
    - eval_datasets
    - train_dataset
    - calibration_datasets
    - save_path
    - calibration_dataset_names
  list_keys:
    - eval_datasets
    - calibration_datasets
    - calibration_dataset_names
  equal_length_groups:
    - - calibration_datasets
      - calibration_dataset_names
